### ISSUE TITLE
Extend getdataframe and TimestepMatrix to > 2 dimensions

### ISSUE THREAD

**Issue by rjplevin** [mimiframework/Mimi.jl#213]
I've already ported James' changes to getdataframe > 2 dimensions (in a private fork) but it won't work until we extend TimestepMatrix as well. Since that is likely to undergo changes in the near future, I've bookmarked this here for now...

**Comment by rjplevin** [comment]
Implemented TimestepArray, and changed TimestepVector and TimestepMatrix to be specializations of this (with number of dimensions, N, bound to 1 or 2, respectively.) I will return to upgrading getdataframe in the near future...

**Comment by cledna** [comment]
Seconding this! Would be very useful for me.

**Comment by davidanthoff** [comment]
Ideally we would always use long form here, and extend to more than two dimensions.

**Comment by lrennels** [comment]
closing because this seems to be done already, see the test file `test_getdataframe`
