### ISSUE TITLE
Add support for sensitivity analysis

### ISSUE THREAD

**Issue by davidanthoff** [mimiframework/Mimi.jl#322]
Relevant Links and Information

**Software Packages**
https://github.com/mstobb/VarianceBasedSensitivity.jl

https://github.com/davidanthoff/PyRhodium.jl (wrapper for https://github.com/Project-Platypus/Rhodium)

https://github.com/SALib/SALib (details below, see GitHub page for paper links)

- Sobol Sensitivity Analysis ([Sobol 2001], [Saltelli 2002], [Saltelli et al. 2010])
- Method of Morris, including groups and optimal trajectories ([Morris 1991], [Campolongo et al. 2007])
- Fourier Amplitude Sensitivity Test (FAST) ([Cukier et al. 1973], [Saltelli et al. 1999])
- Random Balance Designs - Fourier Amplitude Sensitivity Test (RBD-FAST) ([Tarantola et al. 2006], [Elmar Plischke 2010], [Tissot et al. 2012])
- Delta Moment-Independent Measure ([Borgonovo 2007], [Plischke et al. 2013])
- Derivative-based Global Sensitivity Measure (DGSM) ([Sobol and Kucherenko 2009])
- Fractional Factorial Sensitivity Analysis ([Saltelli et al. 2008])

**Literature**

[Global Sensitivity Analysis: The Primer](http://www.andreasaltelli.eu/file/repository/A_Saltelli_Marco_Ratto_Terry_Andres_Francesca_Campolongo_Jessica_Cariboni_Debora_Gatelli_Michaela_Saisana_Stefano_Tarantola_Global_Sensitivity_Analysis_The_Primer_Wiley_Interscience_2008_.pdf)

Saltelli, Andrea, and Beatrice D’Hombres. "Sensitivity analysis didn’t help. A practitioner’s critique of the Stern review." Global Environmental Change 20.2 (2010): 298-302.
MLA | Saltelli, Andrea, and Beatrice D’Hombres. "Sensitivity analysis didn’t help. A practitioner’s critique of the Stern review." Global Environmental Change 20.2 (2010): 298-302.

Saltelli, Andrea, Daniele Vidoni, and Massimiliano Mascherini. "Recommended practices in global sensitivity analysis." Uncertainties in Environmental Modelling and Consequences for Policy Making. Springer, Dordrecht, 2009. 183-202.

Saltelli, Andrea, and Paola Annoni. "How to avoid a perfunctory sensitivity analysis." Environmental Modelling & Software 25.12 (2010): 1508-1517.

**Comment by lrennels** [comment]
Per replicating code from SALib, we are planning to replicate code from methods presented in SALib and convert them to Julia.  One goal will be trying to improve the API so that users can indicate which method they wish to use and things will work under the hood (further discussion with @rjplevin).
