### ISSUE TITLE
helper components in wrong module (v1.0)

### ISSUE THREAD

**Issue by corakingdon** [mimiframework/Mimi.jl#336]
In julia v0.6, helper components `adder`, `ConnectorCompVector`, and `ConnectorCompMatrix` existed in the Main module, as a result of them being loading during the `__init__()` function, as explained in "src/components/README.md".

I haven't tried to figure out why yet, but just noticed that in julia v1.0, these components are loaded in the Mimi module, not the Main module. Example repl in v1.0:

```
julia> using Mimi
[ Info: Loading Cairo backend into Compose.jl
[ Info: new component Mimi.adder
[ Info: new component Mimi.ConnectorCompVector
[ Info: new component Mimi.ConnectorCompMatrix

julia> adder
ERROR: UndefVarError: adder not defined

julia> Mimi.adder
Mimi.adder

julia> Main.adder
ERROR: UndefVarError: adder not defined
```

**Comment by rjplevin** [comment]
That strikes me as a bug fix. It made more sense that they should be loaded in the package in which they were defined!

**Comment by ckingdon95** [comment]
Ah okay, makes sense to me, just didn't realize it was intentional! Will just have to make adjustments to model-specific code that makes use of adder.

**Comment by ckingdon95** [comment]
@rjplevin so does this sentence in "src/components/README.md" still make sense:

"Note that components loaded by `__init__()` are loaded by the `Main` module, not the `Mimi` module. So to place components defined here in `Mimi`, prefix the component names with `Mimi.`"

Or should it be something more like:
"Note that components loaded by `__init__()` are loaded by the `Mimi` module. To use them in other modules, prefix their name with `Mimi.`."

I'm not sure I fully understand how the module loading and referencing works if the first one is true. Are they being loaded in the Main module or the Mimi module?
