### ISSUE TITLE
better timestep comparison handling run_timestep

### ISSUE THREAD

**Issue by lrennels** [mimiframework/Mimi.jl#337]
Think of a clean way to handle the types of comparisons in `run_timestep`

- the timestep is ==, >, < a year
- the time is ==, >, > an int
- perhaps an easier way to access `t.t` (@FrankErrickson)

**Comment by ckingdon95** [comment]
So for this one, we still want to add `<, >, =` comparisons for the new `TimestepIndex` and `TimestepValue` types to compare with `AbstractTimesteps` right?

**Comment by lrennels** [comment]
Yep I think that's right!  It's on me, I just haven't gotten to it.
