### ISSUE TITLE
Better user experience ideas

### ISSUE THREAD

**Issue by ckingdon95** [mimiframework/Mimi.jl#347]
This Issue is a space to add notes on discussions for better user-experience ideas. The main task items are summarized below:

Tutorials and Documentation

- [x] Clarify the use of models as modules and/or packages in the documentation, perhaps in the tutorials.
- [x] Look into the various tech options for tutorials including Binder, CoLab, Jupyter Notebook, Literate,jl, etc. to enhance and ease the use of tutorials and the running of their code.
- [x] Clarify in the MCS documentation how to do the following:
        - assign a parameter a distribution with known shape parameters
        - assign a parameter a user-specified vector of numbers
        - assign correlated parameters
- [x] Create a Mimi forum (UPDATE: https://forum.mimiframework.org)
- [x] Create a set of simple tutorials (UPDATE: four tutorials created)

Functionality 
- [x] Allow setting a Dimension with an Array of type Any, if it can be converted to a DimensionKeyType
- [x] Allow adding random variables to a sim (currently, if I want to use an already defined simulation but just add one more variable, I just have to copy the text and create a new definition)
- [x] implement mean(TimestepArray, Int) to be used in run_timestep functions
- [x] Don't require an output_dir be provided to run_sim if the user didn't define any save variables in the mcs

**Comment by FrankErrickson** [comment]
The user tutorial would benefit from a few more lines about how models are created/used.  Right now, it goes into depth about individual components and functions (e.g. `set_param!`, but doesn't discuss (at least I couldn't find) anything on how models are now defined as `modules`, you need to use the `export` command, and then you eventually end up calling `use my_model` when it's in this module set up.  

I'm assuming this is to have Mimi models act more like Julia packages, but I just had to look at RICE2010 code to understand what was going on.  And even then, the RICE2010 module exported some functions that were defined elsewhere and are not Mimi related (`getrice2010parameters`), so I wasn't really sure what's going on there.

**Comment by lrennels** [comment]
From our discussions 11/16/2018:

It may be useful to create a very detailed, line by line **Tutorial** walking through a few different steps for a first experience user.  For example, the tutorials could include:

1. Steps to download and run a registered model such as fund, get results, and look at the results via UI.
2. Steps to modify the downloaded registered model from (1)
3. Steps to create your own model

We will also need to decide here how we would like to present these tutorials.  We could use plane Markdown, Jupiter Notebook, Google's [Colab](https://colab.research.google.com), [Binder](https://mybinder.org), etc.  For now we will stick to clean Markdown and go from there.

An example of a tutorial:  https://pygcam.readthedocs.io/en/master/tutorial1.html

**Comment by lrennels** [comment]
Improve the forum and discussion options for Mimi (Lisa starting this by asking users what would be most useful)

**Comment by FrankErrickson** [comment]
I can delete this suggestion if it's already being implemented (didn't see it anywhere else), but I thought the current Monte Carlo set-up allows you to set a distribution for a given parameter?

I almost never have a known distribution for my uncertainty runs.  Usually, I have a vector of values I calculated somewhere else and I want to run the Mimi model once for each element of that vector.  So it'd be great if the Monte Carlo could take either (1) distributions with known shape parameters or (2) a user-specified vector of numbers for a given parameter.

One last thought, it'd be nice to be able to allow for correlated parameters.  For instance, some way to assign a multi-dimensional distribution to several different parameters.

**Comment by rjplevin** [comment]
@FrankErrickson, the MCS framework already supports pre-computed trial data, distributions with known shapes, and rank correlation for parameters -- at least drawn using Latin Hypercube Sampling, though this could be made to work for any vectors of values.

**Comment by lrennels** [comment]
From Cora in the beginning of conversation:

Wanted to start a place to add ideas when we think of them.

- Allow setting a Dimension with an Array of type Any, if it can be converted to a DimensionKeyType
- Allow adding random variables to an MCS (currently, if I want to use an already defined MCS but just add one more variable, I just have to copy the text and create a new definition)
- Don't require an output_dir be provided to run_mcs if the user didn't define any save variables in the mcs
- implement mean(TimestepArray, Int) to be used in run_timestep functions

**Comment by lrennels** [comment]
Just came across https://github.com/fredrikekre/Literate.jl. I think that might be a good choice for our tutorials etc. I'd say it can wait until the binder situation works, but once we have that up and running, it might make sense to use it.
