### ISSUE TITLE
Stacktrace line numbers in @defcomp Macro

### ISSUE THREAD

**Issue by lrennels** [mimiframework/Mimi.jl#374]
This most recently came up when I was helping to debug some code for Helen and found that the stacktrace for the `missing` access uses the macro expansion line numbers, making it cumbersome to hunt down which indexing expression causes a problem.  Maybe this is just the way it is, especially without a debugger, but we could brainstorm a way to improve it if possible.

**Comment by rjplevin** [comment]
A simple one-line fix (for each of run_timestep and init) cures this. See new PR.

**Comment by lrennels** [comment]
I am reopening this issue per this discussion: https://forum.mimiframework.org/t/improve-missing-data-error-message/96/3 where the error message doesn't seem to be correct ... but it seems we should have solved this here?
