### ISSUE TITLE
Optimize dimension order?

### ISSUE THREAD

**Issue by rjplevin** [mimiframework/Mimi.jl#388]
Currently we require `time` to be the first dimension, if it occurs. There are two issues with this:
1. Users' code must conform to this (there is a PR for an error message if not in right order)
2. We might get better performance with `time` as the last dimension

Look into mods to our `setindex` and `getindex` functions to see if we can re-order easily behind the scenes, also allowing the user to specify dimensions however they like.

**Comment by jrising** [comment]
I was open another issue on this front.  Relaxing this requirement is quite a pressing need for updating my model, which is designed entirely with time as the last dimension.

**Comment by lrennels** [comment]
@jrising we discussed this today, @ckingdon95 will look at how much of a lift this will be.  We know it's pressing so we'll look ASAP!

**Comment by jrising** [comment]
Thanks for looking into this.  I definitely appreciate it.

**Comment by ckingdon95** [comment]
@jrising I'm looking at this now! One quick questions as I'm starting to try this out: In your model where time is the last dimension, is this reflected in all of your `@defcomps` and `run_timestep` functions? i.e. parameters are defined as `Parameter(index=[r, time])` and then during run timestep they are referenced as `p.paramname[r, ts]` accordingly?

**Comment by jrising** [comment]
I'm not sure what you're asking.  The alternatives to saying p.param[r, t] that I can think of are to say p.param[q, r, s, t] (when there are more dimensions), or saying things like p.param[q, :, :, t] (really all combinations of colon operators in all dimensions except for the time dimension).

**Comment by ckingdon95** [comment]
Sorry yes my question wasn't very clear. I was trying to make sure I was understanding the functionality you want, which is to be able to place the time index in the last (or any position) in each of those two places-- in the initial definition `Parameter(index=[regions, somethingelse, time])` and then also in the run_timestep access with `p.param[r, s, t]`-- and that the positioning must be the same between the two places (but doesn't have to be the same for all parameters and variables). I can't imagine a different way of doing it, but just wanted to make sure that's what you're doing!

**Comment by ckingdon95** [comment]
@jrising I have an implementation that seems to be working, and I opened a pull request here: #434 

I'm going to be cleaning it up and adding more tests, but I think the best test would be for you to try to run your model off of the branch "time" whenever you have the chance!

**Comment by jrising** [comment]
Awesome!  I looked through your PR, and it seems general (with your split_indices approach) and the fact that you changed the type should mean that you got all the necessary changes.  It will take me at least a week to test things though in my model; right now I'm running up against a versioning problem with GlobalSensitivityAnalysis.  But I'm hopeful!

**Comment by lrennels** [comment]
@jrising what is the versioning problem you're getting?

**Comment by jrising** [comment]
It turned out to be a versioning error with trying to use julia 0.7 again.  It went away in Julia 1.*.  I'm still testing things.

**Comment by jrising** [comment]
Okay! Everything has checked out. Thanks for this.

**Comment by ckingdon95** [comment]
Wonderful! We will merge this into master soon.

**Comment by lrennels** [comment]
Done and merged to master in #434!
