### ISSUE TITLE
Tutorial 2 Dependence on DICE2010

### ISSUE THREAD

**Issue by lrennels** [mimiframework/Mimi.jl#396]
DICE2010 is not yet public, so we either need to make it public or base this tutorial on a different model!  After this we want to make sure to complete Tutorial 2's structural updates section, and a more complex example for Tutorial 4.  Add an issue after this once this one closes.

Note: Frank's paper is probably the soonest publication that will make DICE2010 public.

**Comment by FrankErrickson** [comment]
@lrennels In theory I'll have a paper out with DICE2010 in the near future (in academic time).  Not sure how quickly you need the tutorials updated, but perhaps it helps?

**Comment by lrennels** [comment]
@grantmcdermott DICE2010 and DICE2013 are now public
