### ISSUE TITLE
Add a `dimensions` function to the export list or equivalent

### ISSUE THREAD

**Issue by jrising** [mimiframework/Mimi.jl#416]
This is a reboot of Issue #27 .  Currently, the equivalent for the `getindexlabels(model, component, name)` function under the current version of Mimi is to import `parameter_dimensions` and `variable_dimensions`, and call one or the other based on the `parameter_names` list.  I would like to request one of the following options:

1. Export `parameter_dimensions`, `variable_dimensions`, and `parameter_names` so that these are treated as part of the "official" API.
2. Create and export a `dimensions(model, component, name)` function, which internally calls these three functions as needed.

Also, I think I must have missed the discussion where the `getindexlabels` functionality was dropped from the supported (exported) API.  What's the right process here?

**Comment by jrising** [comment]
@lrennels Here's the issue for https://forum.mimiframework.org/t/export-of-parameter-dimensions-variable-dimensions-parameter-names/25

**Comment by jrising** [comment]
@lrennels Actually, this isn't working.  The variable_dimensions (and similar) functions refer to a `comp_id` variable, but the variable is called `comp_name` in those functions.  Should be a quick fix.

**Comment by lrennels** [comment]
@jrising do you mean that your use cases call the functions on a `comp_id` instead of the `Symbol` of the `comp_name`?

**Comment by jrising** [comment]
@lrennels I'm not trying to say anything like that.  I mean that you get an error when you try to call these functions.  It's better to just look at the code:
```
function variable_dimensions(m::Model, comp_name::Symbol, var_name::Symbol)
    var = variable(m, comp_id, var_name)
    return var.dimensions
end
```
So, `comp_id` isn't defined.

**Comment by lrennels** [comment]
@jrising I see, sorry I was confused because this does appear to be a problem only with `variable_dimensions`.  I will fix that now.

**Comment by lrennels** [comment]
#435

**Comment by jrising** [comment]
@lrennels You're right!  I saw that the variable_dimensions and variable_unit problem were coming from the same commit and thought it went further.  Thanks for fixing it!

**Comment by lrennels** [comment]
Of course!  Thank you for pointing it out.
