### ISSUE TITLE
Sobol Simulation Number of Trials

### ISSUE THREAD

**Issue by lrennels** [mimiframework/Mimi.jl#436]
When the Monte Carlo functionality was built out considering only Monte Carlo methods, we made calling `generate_trials` optional, and also made `trials` a required parameter for `run_sim`, indicating how many trials to run.  

Sobol analysis, however **requires** a very specific number of trials, calculated from `N`, `calc_second_order`, and the number of random variables.  If we call `generate_trials!`, that will in turn call `sample!`, which sets `sim.trials` to the proper value.  We can then call `run_sim(sim, sim.trials)` to get the correct number of trials.  This is, however not possible when we don't run `generate_trials!`, and the user would have to know how to compute the proper number.  In general this seems rather fragile.

@rjplevin maybe we can have a design discussion surrounding this, as well as the placement of `sampling(...)` within `@defsim`?  I can do the machinery work but I think we should discuss this in light of the consideration of #423 too.

**Comment by rjplevin** [comment]
Agreed. Do you want to skype before Friday or meet then?

**Comment by lrennels** [comment]
#442
