### ISSUE TITLE
Can we get rid of all calls to `eval`?

### ISSUE THREAD

**Issue by davidanthoff** [mimiframework/Mimi.jl#437]
There are a few cases in the code base where we call `eval`. Can we get rid of them? Some of these happen in macros, and I would think there in particular we should be able to avoid that?

**Comment by rjplevin** [comment]
It would be good to discuss this. I've tried to eliminate the use of `eval`, but there are some cases I wasn't able to resolve easily.

**Comment by rjplevin** [comment]
The only remaining `eval` calls evaluate default parameter values set in `@defcomp`. I think this is ok.
