### ISSUE TITLE
Calling components function before run results in opaque error

### ISSUE THREAD

**Issue by jrising** [mimiframework/Mimi.jl#438]
If you try to call `components(model)` on a model before it is run, you get the error:

```
ERROR: MethodError: no method matching components(::Nothing)
Closest candidates are:
  components(::Model) at /Users/jrising/.julia/packages/Mimi/bsKh8/src/core/model.jl:10
  components(::Mimi.ModelInstance) at /Users/jrising/.julia/packages/Mimi/bsKh8/src/core/instances.jl:28
Stacktrace:
 [1] components(::Model) at /Users/jrising/.julia/packages/Mimi/bsKh8/src/core/model.jl:10
```

Either this shouldn't return an error, or the error should be more clear.

I'm not sure what the use-case for the `components` function is, but when optimizing components, I sometimes never run them (nor even bother to define `run_timestep` functions), so it would be nice not to rely on this.

**Comment by lrennels** [comment]
@jrising (Maybe you figured this out), but the error occurs because calling `components(model)` just wraps and calls `components(model.mi)`, and an un-run model does not have a model instance yet. Do you need to be able to call `components` on an unrun model, or were you mainly pointing out the need for getting the component list of an unrun model?

**Comment by lrennels** [comment]
I suppose this conversation is linked to this one: https://forum.mimiframework.org/t/retrieving-parameter-values/37 we we can also discuss there

**Comment by lrennels** [comment]
We have added an error message with #441, we can discuss a potential need to make calls to an unrun model on the forum and add an other Issue if we come to a decision on an action item.

**Comment by jrising** [comment]
Right: This issue was just to call attention to the lack of an informative error message.  I may at some point need access to the `components` function for an un-run model, but based on the discussion in the forum, it seems like I can just use the `external_params` for now.
