### ISSUE TITLE
Docstring comment on `run_timestep` causes error

### ISSUE THREAD

**Issue by jrising** [mimiframework/Mimi.jl#439]
If you have a docstring on the `run_timestep` function, you get an Element Syntax Error.

That is if you have something like this:
```
@defcomp MyComponent begin
    ....

    """
    Do the thing
    """
    function run_timestep(p, v, d, t)
        ....
    end
end
```

Then you get the error:
```
ERROR: LoadError: LoadError: LoadError: LoadError: Element syntax error: #= /path/to/MyComponent.jl:23 =# Core.:(@doc) "Do the thing\n" function run_timestep(p, v, d, t)
....
```

I'm not certain that docstrings are particularly helpful under new-Mimi, but I'm in the practice using them when I define functions, and I suspect that others will run into this too.

**Comment by rjplevin** [comment]
Fixed.

**Comment by jrising** [comment]
Thanks!
