### ISSUE TITLE
Mimi.load_comps() loads compdefs into Mimi module

### ISSUE THREAD

**Issue by ckingdon95** [mimiframework/Mimi.jl#470]
haven't done much investigating into why this is happening yet, but if I try to use the build int `load_comps` function to load all my component files from a directory, I can't access my component definitions without doing `Mimi.my_comp_name` even though it's being included in the Main module

```
julia> Mimi.load_comps("src/components")

julia> IWG_DICE_co2cycle
ERROR: UndefVarError: IWG_DICE_co2cycle not defined

julia> Main.IWG_DICE_co2cycle
ERROR: UndefVarError: IWG_DICE_co2cycle not defined

julia> Mimi.IWG_DICE_co2cycle
Mimi.ComponentDef(:IWG_DICE_co2cycle, <ComponentId Main.IWG_DICE_co2cycle>, OrderedCollections.OrderedDict(:MAT=>DatumDef(:MAT, Number, Symbol[:time], "", "", :variable, nothing),:ML=>DatumDef(:ML, Number, Symbol[:time], "", "", :variable, nothing),:MU=>DatumDef(:MU, Number, Symbol[:time], "", "", :variable, nothing)), OrderedCollections.OrderedDict(:E=>DatumDef(:E, Number, Symbol[:time], "", "", :parameter, nothing),:mat0=>DatumDef(:mat0, Number, Symbol[], "", "", :parameter, nothing),:ml0=>DatumDef(:ml0, Number, Symbol[], "", "", :parameter, nothing),:mu0=>DatumDef(:mu0, Number, Symbol[], "", "", :parameter, nothing),:b11=>DatumDef(:b11, Number, Symbol[], "", "", :parameter, nothing),:b12=>DatumDef(:b12, Number, Symbol[], "", "", :parameter, nothing),:b21=>DatumDef(:b21, Number, Symbol[], "", "", :parameter, nothing),:b22=>DatumDef(:b22, Number, Symbol[], "", "", :parameter, nothing),:b23=>DatumDef(:b23, Number, Symbol[], "", "", :parameter, nothing),:b32=>DatumDef(:b32, Number, Symbol[], "", "", :parameter, nothing)…), OrderedCollections.OrderedDict{Symbol,Union{Nothing, Dimension}}(:time=>nothing), nothing, nothing)
```

**Comment by rjplevin** [comment]
Which is being included in Main? The component names would have to be exported from Mimi...

**Comment by ckingdon95** [comment]
Since the call to `load_comps` happens in the Main module, I was just thinking that the intended functionality would be that user would be able to access the component definitions from the main module. If instead I just call `include("components/my_comp_name.jl")` for all the components in the directory, then I am able to access the component definitions without the `Mimi.` prefix. Is that not what we would also want `load_comps` to do?

**Comment by rjplevin** [comment]
Apparently, it's loading into Mimi because the `load_comps` method is defined within Mimi. That is not particularly useful... I would have thought the (dynamically) current module would receive the included code, not the module containing the function _calling_ include.

**Comment by rjplevin** [comment]
There is also `Base.include(mod::Module, path::AbstractString)`, which we might want to use to force the code into a desired module. We could have a keyword arg to allow `load_comps` to pass this through....

**Comment by davidanthoff** [comment]
I have to admit that I'm still not a fan of this functionality in general :) I think in general Mimi.jl should not get into the business of loading code files, I think we would better leave that to julia itself. _If_ we wanted to have such functionality, I think it should be in a separate package, because this whole functionality seems really orthogonal to the Mimi story. Maybe a package like that already exists, who knows :)

**Comment by rjplevin** [comment]
I'd be fine with dropping this function. If we want to keep it, we could make it a macro to load into the caller's module.

**Comment by davidanthoff** [comment]
Yes, I'd be in favor of dropping it for now.

**Comment by ckingdon95** [comment]
#570
