### ISSUE TITLE
setindex! in TimestepArrays with Colon doesn't work

### ISSUE THREAD

**Issue by ckingdon95** [mimiframework/Mimi.jl#471]
I think the following is an internal bug. We have implemented `setindex!` functions for `TimestepArrays` with `AnyIndex` (line 268 in "src/core/time.jl" for vectors), but it appears that function is not getting used in the following code, and the values fail to be set. (I haven't tried out the debugger yet to be able to step through and see what function is actually being called in the second line)

```
julia> x=Mimi.TimestepVector{Mimi.FixedTimestep{2005,10}, Float64}(zeros(10))
Mimi.TimestepArray{Mimi.FixedTimestep{2005,10,LAST} where LAST,Float64,1}([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])

julia> x[:].=1
10-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

julia> x
Mimi.TimestepArray{Mimi.FixedTimestep{2005,10,LAST} where LAST,Float64,1}([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
```

**Comment by rjplevin** [comment]
It appears that broadcasting `.=` doesn't result in calling `setindex!` as one would expect. I've been looking for the right method to override, but I haven't found it yet. I'm hoping @davidanthoff has run into this before.

BTW, the Debugger wasn't helpful for this:
```
julia> f() = (x[:] .= 100)
f (generic function with 1 method)

julia> @enter f()
In f() at REPL[27]:1
>1  f() = (x[:] .= 100)

About to run: (Base.Broadcast.dotview)(<suppressed 155 bytes of output>, Colon())
1|debug> n
In f() at REPL[27]:1
>1  f() = (x[:] .= 100)

About to run: return [100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0]
1|debug> n
10-element Array{Float64,1}:
 100.0
 100.0
 100.0
 100.0
 100.0
 100.0
 100.0
 100.0
 100.0
 100.0
```

**Comment by rjplevin** [comment]
I believe the answer is [here](https://discourse.julialang.org/t/how-to-customize-the-new-broadcasting-infrastructure-in-v0-7/11322/3), though it's buried pretty deep... still looking.

**Comment by rjplevin** [comment]
The magic sauce:

`Base.dotview(v::Mimi.TimestepArray, args...) = Base.dotview(v.data, args...)`.

**Comment by ckingdon95** [comment]
amazing! thank you!

**Comment by ckingdon95** [comment]
#472
