### ISSUE TITLE
Update parameter in Monte Carlo run

### ISSUE THREAD

**Issue by grantmcdermott** [mimiframework/Mimi.jl#474]
The [package documentation](https://www.mimiframework.org/Mimi.jl/stable/tutorials/tutorial_2/) provides a nice example of how to update a parameters using the `!update_param` API method. However, near as I can tell, this method only works for the deterministic version of the model(s). I'm looking for a way to update parameters in the Monte Carlo version of the model.

Using [MimiPAGE2009.jl](https://github.com/anthofflab/MimiPAGE2009.jl) as an example, say I want to edit the TCR parameter (i.e. `tcr_transientresponse` [here](https://github.com/anthofflab/MimiPAGE2009.jl/blob/master/src/mcs.jl)). I thought that adding the below line to the `do_monte_carlo_runs()` function might do the trick, but I just get a bunch of error messages:
```
update_param!(mcs, :tcr_transientresponse, Normal(0.0, 0.1)) ## Try crazy low TCR
```
Any suggestions for a better method are much appreciated.

**Comment by ckingdon95** [comment]
Hi Grant, you are correct, the `update_param!` function is meant to be used on a deterministic model, not within the Monte Carlo simulation. If I am interpreting your intention correctly, you would like to sample very low values of TCR throughout the simulation (each trial with a different value from your normal distribution). 

In order to do this, you should modify the definition for the `tcr_transientresponse`  parameter's distribution that is definied within the `@def_sim` macro where all of PAGE's random variables are defined. On line 46 of "src/mcs.jl" in the MimiPAGE2009 package, the random variable is defined as the following:
```
tcr_transientresponse = TriangularDist(1, 2.8, 1.3)
```
Simply change this to your desired distribution
```
tcr_transientresponse = Normal(0.0, 0.1)
```
And then when you run the simulation (using the `do_monte_carlo_runs` function if desired) it will sample from this new distribution instead.

Let me know if you have any other questions about how to use this, I'm happy to help!

**Comment by grantmcdermott** [comment]
Super, thanks Cora. That approach was going to be my fallback, so it's good to have it sanity checked by someone in the know.

**Comment by grantmcdermott** [comment]
PS - It might be helpful to add a note to the docs about the limitations of `!update_param` to the deterministic case. Cheers!

**Comment by davidanthoff** [comment]
I think it would be good to come up with a more interactive API for this, though. I think in general if we have a situation where someone wants to run an alternative specification, we should make sure that we have a way to do this that does _not_ involve changing a file from the original model package.

**Comment by grantmcdermott** [comment]
Yes, as a user that would be my strong preference too.

Similarly, I'm not entirely sure how to generate a SCC calculation using the stochastic framework at present. (See also https://github.com/mimiframework/Mimi.jl/issues/411). Say I follow [this example](https://www.worldscientific.com/doi/pdf/10.1142/S2010007817500099) and want to generate an emissions pulse of 1 million metric tons of carbon in 2020. Do you have any suggestions for the best way to do this currently? (I'm specifically using MimiPAGE09 if that makes a difference.)

**Comment by ckingdon95** [comment]
@davidanthoff Yes I agree, I've been saying I think we should add methods to modify a Simulation (such as add or change random variable distributions, and add or change with variables get saved)

@grantmcdermott I can get back to you in a bit about example code for SCC calculations in PAGE. The code doesn't currently exist in the MimiPAGE2009 package, but we are hoping to update with it soon

**Comment by lrennels** [comment]
Per our conversation today, we would like to add options to:

- add a random variable
- remove a random variable
- update a random variable
- update or change the save list

**Comment by rjplevin** [comment]
I've implemented much of this already, but some of it gets complicated. Modifying the save list is straightforward. The RVs are more complicated. Consider the example below.

Random variables can be named or anonymous. In the anonymous case, an Distribution is associated with a parameter by assignment, multiplication, or addition. In these cases, an internal RV is created from the variable name, "!" and an incrementing integer to ensure uniqueness, e.g., `:depk!8`. This is fully equivalent to the user defining this as `rv(depk!8) = ...` and then referencing `depk!8` where the distribution is now given. It just saves some needless redundancy. 

As originally conceived this approach with anonymous RVs was all "internal", but unless we want to redesign this, we will have to expose these generated names to the user to allow updates. Not a big deal, I suppose.

It's easy to support swapping out the RV for another, provided the name doesn't change. Deleting an RV should delete the `TransformSpec` to avoid referencing the defunct distribution. Adding an RV will require providing the `TransformSpec` as well.

```julia
julia> sim = @defsim begin
           # Define random variables. The rv() is required to disambiguate an
           # RV definition name = Dist(args...) from application of a distribution
           # to an external parameter. This makes the (less common) naming of an
           # RV slightly more burdensome, but it's only required when defining
           # correlations or sharing an RV across parameters.
           rv(name1) = Normal(1, 0.2)
           rv(name2) = Uniform(0.75, 1.25)
           rv(name3) = LogNormal(20, 4)
           # assign RVs to model Parameters
           share = Uniform(0.2, 0.8)
           sigma[:, Region1] *= name2
           sigma[2020:5:2050, (Region2, Region3)] *= Uniform(0.8, 1.2)
           depk = [Region1 => Uniform(0.08, 0.14),
                   Region2 => Uniform(0.10, 1.50),
                   Region3 => Uniform(0.10, 0.20)]
           sampling(LHSData, corrlist=[(:name1, :name2, 0.7), (:name1, :name3, 0.5)])
           
           # indicate which parameters to save for each model run. Specify
           # a parameter name or [later] some slice of its data, similar to the
           # assignment of RVs, above.
           save(grosseconomy.K, grosseconomy.YGROSS, emissions.E, emissions.E_Global)
       end
Simulation{LHSData}
  trials: 0
  current_trial: 0
  rvdict:
    name1: RandomVariable{Normal{Float64}}
    name2: RandomVariable{Uniform{Float64}}
    name3: RandomVariable{LogNormal{Float64}}
    share!6: RandomVariable{Uniform{Float64}}
    sigma!7: RandomVariable{Uniform{Float64}}
    depk!8: RandomVariable{Uniform{Float64}}
    depk!9: RandomVariable{Uniform{Float64}}
    depk!10: RandomVariable{Uniform{Float64}}
  translist:
    TransformSpec(:share, :(=), :share!6, Any[])
    TransformSpec(:sigma, :*=, :name2, Any[Colon(), :Region1])
    TransformSpec(:sigma, :*=, :sigma!7, Any[2020:5:2050, Symbol[:Region2, :Region3]])
    TransformSpec(:depk, :(=), :depk!8, Any[:Region1])
    TransformSpec(:depk, :(=), :depk!9, Any[:Region2])
    TransformSpec(:depk, :(=), :depk!10, Any[:Region3])
  savelist:
    (:grosseconomy, :K)
    (:grosseconomy, :YGROSS)
    (:emissions, :E)
    (:emissions, :E_Global)
  nt_type: NamedTuple{(:name1, :name2, :name3, :share!6, :sigma!7, :depk!8, :depk!9, :depk!10),NTuple{8,Float64}}
  0 models
  1 results dicts
LHSData(Tuple{Symbol,Symbol,Float64}[(:name1, :name2, 0.7), (:name1, :name3, 0.5)])
```

**Comment by davidanthoff** [comment]
Maybe the solution is to not allow modification of anonymous RVs, but instead an option to interactively associate a parameter with a new distribution. That would create a new RV, the code could detect that the old, anonymous RV is no longer used and remove that.

**Comment by lrennels** [comment]
@grantmcdermott we have added some (unexpected) functions to address this request.  

- function PR: #478 
- docstring PR for those functions: #500 
- adding the functions in to the documentation: #501

**Comment by grantmcdermott** [comment]
Super, thanks @lrennels and co. Just leaving for vacation, but look forward to digging into these when I get back.

**Comment by lrennels** [comment]
@grantmcdermott we have written doc strings for this but not full documentation, and as a team will be firming up our API for uncertainty and evaluating the current design, since only though trying it out are we finding how to best simplify it for users, but I will of course keep everyone updated through PSAs. That said if you do try out the functionality please don’t hesitate to get in touch. One note is the importance of using the addtransform function in conjunction with addRV!
