### ISSUE TITLE
Make Mimi less verbose

### ISSUE THREAD

**Issue by ckingdon95** [mimiframework/Mimi.jl#480]
The places I can think of that give warnings (that it seems like @davidanthoff wants us to remove) are:
- When you update the time dimension
- When you replace a component and it removes an external parameter connection that is no longer in the new component

**Comment by davidanthoff** [comment]
We could just replace `@warn` with `@debug`? I think then there is some way to switch that sort of output on? Not sure, though.

**Comment by rjplevin** [comment]
The time dimension warning is gone in the composite version. The removal of the external parameter seems to warrant a warning.

**Comment by ckingdon95** [comment]
For now, turn them off by turning them into debug messages.

In the medium term, we would like to be able to switch verbose on and off:
- `Mimi.verbose(true)`
