### ISSUE TITLE
Provide a nice show method for Model

### ISSUE THREAD

**Issue by davidanthoff** [mimiframework/Mimi.jl#485]
We used to have that, now it seems to be gone. I think @rjplevin mentioned that the composite branch has it again, but it would be good to have something for the workshop.

**Comment by rjplevin** [comment]
I could back-port this from the composite if desired. The truth is that the output is still quite unwieldy for non-trivial models. The `show` API allows you to set a `:compact` attribute in the `IO` object that the `show` method can test for to trim its output, but I haven't done that yet.

Is this a priority for the workshop?

**Comment by davidanthoff** [comment]
I think we need something nice for the workshop. It could be just a static string a la `Mimi Model` or something like that for starters. Right now it just outputs this wall of internal details, very early in any interactive demo that is really not great.
