### ISSUE TITLE
Function to return a plot should not be called `explore`

### ISSUE THREAD

**Issue by davidanthoff** [mimiframework/Mimi.jl#486]
I think `explore` should be reserved for the interactive UI. We should find a different name for the function that returns a VegaLite.jl plot object.

The obvious candidate would be `plot`, but then we run into conflicts with other packages... So we need something better :)

**Comment by lrennels** [comment]
Hmm yes I thought about this too.  I think `plot` is too likely to cause conflicts, as you say.  Perhaps something like `display`?

**Comment by rjplevin** [comment]
Alternatively, we could just not export `plot`. I'm skeptical that we'd find a better name than `Mimi.plot`. As always, a user can import it if it doesn't create conflicts in their case.

**Comment by lrennels** [comment]
That is true, we could continue to export `explore` but not `plot`.

**Comment by lrennels** [comment]
Handled in #492

**Comment by davidanthoff** [comment]
Yep, I agree with the reasoning pro `plot`!
