### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by davidanthoff** [mimiframework/Mimi.jl#502]
I think we should significantly shorten the README. Here are some ideas:
- Remove any info that is already on https://www.mimiframework.org/ (for example list of models etc.), instead just add a link to https://www.mimiframework.org/ to the README.
- Move installation an registry information into the documentation.

I think essentially there should be just one paragraph saying what Mimi.jl is, links to the homepage and docs, and the contributing and ack section.

Couple smaller things:
- We should have a link to the forum up there.
- I think we should remove the link to the latest docs, just have the link to the stable version.

**Comment by lrennels** [comment]
#504
