### ISSUE TITLE
problem with addRV!

### ISSUE THREAD

**Issue by ckingdon95** [mimiframework/Mimi.jl#505]
It appears that addRV! does not fully work. It looks like the added Random Variable does get added to the Simulation's rvdict, but no appropriate transformation spec is added to the translist, so the values do not actually get applied to the appropriate model parameters in the simulation. here is an example to try:
```
using Mimi
using Distributions

function _get_sim()
    sim = @defsim begin
        a = Normal()
    end
    return sim 
end

@defcomp MyComp begin
    a = Parameter(default=-99)
    b = Parameter(default=-99)
end

function _post(sim::Simulation, trialnum::Int, ntimesteps::Int, tup::Union{Nothing, Tuple})
    m = sim.models[1]
    println(m[:MyComp, :a], ", ", m[:MyComp, :b])
end

sim = _get_sim()
Mimi.addRV!(sim, :b, Normal())

m = Model()
set_dimension!(m, :time, 2000:2010)
add_comp!(m, MyComp)

set_models!(sim, [m])
generate_trials!(sim, 10, filename="trials.csv")
run_sim(sim; trials=10, post_trial_func=_post)
```

The result looks like this, where :a is being sampled but :b is not:
```
-0.06854051826543264, -99.0
-0.6752877312413286, -99.0
-0.10279405263603304, -99.0
-2.4520648175283575, -99.0
0.6704755365223157, -99.0
0.687045892250668, -99.0
-2.230271194326101, -99.0
0.13814666269821685, -99.0
-0.5639991588869054, -99.0
-1.500560941156566, -99.0
```
You can also see the Simulation fields:
```
julia> sim
Simulation{MCSData}
  trials: 10
  current_trial: 10
  current_data: (a!2 = 0.6046669535376429, b = 0.34179965596839884)
  rvdict:
    a!2: RandomVariable{Mimi.SampleStore{Float64}}
    b: RandomVariable{Mimi.SampleStore{Float64}}
  translist:
    TransformSpec(:a, :(=), :a!2, Any[])
  nt_type: NamedTuple{(:a!2, :b),Tuple{Float64,Float64}}
  1 models
  1 results dicts
MCSData()
```

**Comment by rjplevin** [comment]
This is mainly a documentation failure. The second arg to `addRV` (I should rename this `add_rv` as per recent discussions...) is the name of the RV, not the name of the parameter. Yes, you have specify the transform, which also associates a parameter with an RV.

Maybe we should add a function that calls both of these and takes a bunch of kw args, and we assume some defaults. Maybe in the simplest form (no kw args) it sets an "assignment" transform for scalars (only) that directly assign the values from an RV or distribution.

**Comment by ckingdon95** [comment]
Ah sorry I totally missed the second part of how to use this... I did not realize you have to call `addTransform` for each `addRV`!

**Comment by rjplevin** [comment]
No worries! I may have misinterpreted to goal of this API. I thought we'd continue to rely on `@defsim`, with the API used to make occasional tweaks. If the intention is to use this entirely to build up a simulation, we might want to simplify it somewhat.
