### ISSUE TITLE
Make `components`, `variables` and `parameters` user exploration facing

### ISSUE THREAD

**Issue by davidanthoff** [mimiframework/Mimi.jl#509]
It used to be that one could call these functions and get somewhat nice lists, thus making them quite useful for interactive exploration of models. Now they mainly return complicated types :)

It might be enough to add some `show` methods, or maybe we need more. But it would be good if one could use these functions for interactively exploring a model structure.

**Comment by rjplevin** [comment]
I've implemented a substantial `show` infrastructure in the Mimi `class-based` (composites) branch. It would be a pain to back-port it given all the type changes.

I continue to make progress on Components, but it's been hard doing this is small bites...

**Comment by davidanthoff** [comment]
For 1.0: remove exports of these functions, i.e. we don't expose an API to explore the structure of a model for now.
