### ISSUE TITLE
"sum" component

### ISSUE THREAD

**Issue by davidanthoff** [mimiframework/Mimi.jl#52]
Some way to sum outputs from a number of components and input the sum as a parameter into another component. Maybe also have the option to specify any function, not just `sum`, for the aggregation step.

**Comment by davidanthoff** [comment]
I think we should leave this open for now. We might find a better way than a sum component, but something like this would be very helpful.

**Comment by lrennels** [comment]
@davidanthoff closing this because it's a duplicate
