### ISSUE TITLE
Rename `marginal` attribute of MarginalModel

### ISSUE THREAD

**Issue by jrising** [mimiframework/Mimi.jl#530]
The attributes of the `MarginalModel` object are confusingly (and incorrectly) named. The `marginal` attribute does not contain itself some kind of marginal model object, or anything like it. Rather, it contains a perturbed model. I propose that the `marginal` attribute be renamed `perturbed`.

**Comment by davidanthoff** [comment]
Another option might be to rename the fields to `model1` and `model2`.

**Comment by ckingdon95** [comment]
or `base` and `modified`.

**Comment by davidanthoff** [comment]
@jrising do you have a preference for one of these options? We are all indifferent here, but happy to change it.

**Comment by jrising** [comment]
I think that `base` and `modified` are sensible, if we don't want to assume that a `MarginalModel` was created only by the SCC process. That would be my preference.

**Comment by lrennels** [comment]
This would be breaking, so we we should make a call here.

**Comment by davidanthoff** [comment]
Indeed. I thought we had made a decision at some point? I have to admit that I don't care _that_ much. But, whatever we decide now will stick :)

**Comment by ckingdon95** [comment]
Yeah we decided to go with "modified". I will do this, it will be quick, I was just going to wait until Rich's stuff is merged to make it even easier!

**Comment by jrising** [comment]
Thanks for doing this! I don't mind the breaking change, but it might be nice to do a "gradual deprecation", where the `marginal` attribute becomes an alias for `modified` that also prints out a warning telling people to switch over before the release after this one.

**Comment by ckingdon95** [comment]
Sounds good, we will do the deprecated version as well

**Comment by arnavgautam** [comment]
I can work on this
