### ISSUE TITLE
d.time should return AbstractTimestep things

### ISSUE THREAD

**Issue by davidanthoff** [mimiframework/Mimi.jl#538]
I think that `d.time` inside `run_timestep` should return things that one can use to index into variables and parameters directly. Right now it seems to return `Int`s instead, which we should actively discourage for indexing use.

Ideally things like `first(d.time)` and `last(d.time)` would just work. And then we should try to get something like `first(d.time):last(d.time)` to work to get a range that includes every timestep.

**Comment by ckingdon95** [comment]
I'll plan to work on this after we finish #551. After that is merged, we will have multiple types of `Timestep` things that can be used as indexes, so we'll have to decide which kind `d.time` should return

**Comment by ckingdon95** [comment]
We decided that this should not be either of the new `AbstractTimesteps` (`TimestepValue` or `TimestepIndex`). This should return either a `VariableTimestep` or a `FixedTimestep`, whichever it is to match the `t` being passed to the `run_timestep` function. @davidanthoff, I think I will just implement this as an array, unless you choose otherwise! currently d.dimname returns vectors

**Comment by rjplevin** [comment]
Are the new indexers `AbstractTimestep`s? This seems odd to me, since they have to be resolved against an (old) `AbstractTimestep`. I think we need a new abstract type.

**Comment by ckingdon95** [comment]
Oh I'm not sure, that implementation isn't finished yet. But maybe you should let Lisa know here: https://github.com/mimiframework/Mimi.jl/pull/551

**Comment by davidanthoff** [comment]
Shouldn't all four of these inherit from `AbstractTimestep`?

I think returning an array is fine for now. We can later still decide to change that to something more efficient.

**Comment by rjplevin** [comment]
> Shouldn't all four of these inherit from `AbstractTimestep`?

There are methods that make sense for `FixedTimestep` and `VariableTimestep` that cannot work with the new `TimestepValue` or `TimestepIndex`, which are not themselves timesteps (in the sense of the prior two), but indices into the time dimension.

What exactly is gained by unifying these under `AbstractTimestep`? The usage of the two pairs is necessarily different.

**Comment by rjplevin** [comment]
Maybe we should rename `FixedTimestep` and `VariableTimestep` to be `FixedTimeDimension` and `VariableTimeDimension`?

**Comment by davidanthoff** [comment]
I'm not sure :) Maybe it all doesn't matter that much in any case, actually? The only reason to have an abstract type at all is if we use that for dispatch somewhere, right?

**Comment by rjplevin** [comment]
Yes, exactly. I don't see a case for a method that would operate on all four of these. The new types need the old types to resolve to an actual timestep, so the API will generally be different.

**Comment by ckingdon95** [comment]
@davidanthoff In the following example, should `d.time` (accessed during a `run_timestep` function) return an array of timesteps for the whole time dimension (2000 to 2100), or should it only return an array of timesteps for the length that will be run (2000 to 2050)?
```
m = Model()
set_dimension!(m, :time, 2000:2100)

# add components

run(m, ntimesteps = 51)
```
My guess is that is should only return the length that's being run, but let me know what you think!

**Comment by lrennels** [comment]
I'd probably agree with you @ckingdon95, seems like just the time steps for the length that will be run if that's possible.

**Comment by davidanthoff** [comment]
Yes, I agreed, only the timesteps that are being run!
