### ISSUE TITLE
Replace integration guide for v1.0.0

### ISSUE THREAD

**Issue by ckingdon95** [mimiframework/Mimi.jl#626]
I'm wondering if at a certain point we should delete or archive the Integration Guide for v0.5 that is still part of our documentation. Related, we should probably create a new one for changes being made in v1.0

**Comment by lrennels** [comment]
@ckingdon95 great idea, we can archive that guide and then replace it with one for v1.0

**Comment by lrennels** [comment]
#708

**Comment by lrennels** [comment]
Reminder to look at the changes I'm making in the removing deprecation branch as a guide for what has been changed.
