### ISSUE TITLE
replace_comp! functionality with default parameters

### ISSUE THREAD

**Issue by ckingdon95** [mimiframework/Mimi.jl#644]
example:
```julia
using Mimi

@defcomp A begin
    p1 = Parameter(default=3)
    p2 = Parameter()
end

@defcomp B begin
    p1 = Parameter(default=4)
    p2 = Parameter()
end

m = Model()
set_dimension!(m, :time, 10)
add_comp!(m, A)
set_param!(m, :A, :p1, 5)
set_param!(m, :A, :p2, 6)
replace_comp!(m, B, :A)
run(m)
m[:A, :p1]
```
The above code returns a value of 4 for p1, even though the parameter value had been set to 5 before the replacement, and other external values that are set such as for p2 are maintained. Is this the behavior we want? In my opinion, this is a bug, but I'm curious what others think.

**Comment by davidanthoff** [comment]
I agree, this looks like a bug to me.

**Comment by rjplevin** [comment]
I'm not so sure. 
- Should `replace_comp!` not be equivalent to removing the old and then adding the new comp?
- Should `replace_comp!` re-connect all same-named params and then delete params that aren't in the replacement?
- Or should it be an error if the replacement comp has different params than the original?

I think we need to address this by first defining the semantics we want.

**Comment by davidanthoff** [comment]
I think the semantics that we keep all existing connections and parameter sets intact to the extent possible when we replace a comp makes most sense, at least that is what would be most useful for the scenarios where I would use this function.

**Comment by ckingdon95** [comment]
I think this has been resolved, because there was a change sometime on master since v0.9.5 where defaults are no longer explicitly set in the model at the time of `add_comp!`, and are instead not set till build time. This results in the desired behavior for a replaced component: it is the same as just deleting the old and adding the new, but any connections (internal or external) that had already been set are still preserved. I can add an explicit test of this behavior though if we are decided on how this should behave.
