### ISSUE TITLE
Fix bug in colon indexing to timestep arrays

### ISSUE THREAD

**Issue by lrennels** [mimiframework/Mimi.jl#658]

**Comment by ckingdon95** [comment]
@rjplevin @lrennels can someone give a one sentence explanation of this one?

**Comment by lrennels** [comment]
@ckingdon95 We thought that there was a situation where indexing into a `TimestepArray` with a `:` in the `ti` index caused a deprecation warning (and thus eventual error), but we want to be able to use the `:`.  As it turns out I think it was just a bug in the testing suite not in the code itself.  Make sense?
