### ISSUE TITLE
mimi-next branches for models

### ISSUE THREAD

**Issue by lrennels** [mimiframework/Mimi.jl#675]
The following models are in the `test_all_models.jl` script. We have started `mimi-next` branches for some, with PRs labeled something like `Update for Mimi v1.0.0`

Checked off if running ...

these are packages:
- [x] MimiDICE2010 - Cora
- [x] MimiDICE2013 - Lisa
- [x] MimiRICE2010 - Lisa
- [x] MimiFUND - Cora
- [x] MimiPAGE2009 - Cora & Lisa

repos:
- [x] MimiDICE2016 - Lisa

(not doing these for now:)
- MimiSNEASY
- MimiFAIR
- MimiMAGICC 
- MimiHECTOR

**Comment by davidanthoff** [comment]
I just tried to run `contrib/test_all_models.jl` (I updated it to hopefully use all the right versions).

MimiRICE2010 passes, but MimiDICE2010, MimiFUND and MimiPAGE2009 fail. I didn't run any of the other models.

**Comment by davidanthoff** [comment]
Another todo here:
- [ ] Make the min version of Mimi in all the `mimi-next` branches `0.10`.

**Comment by lrennels** [comment]
This is done!  When Mimi is fully updated, then the test all models CI test should begin to pass.
