### ISSUE TITLE
fix getindex methods for composites

### ISSUE THREAD

**Issue by ckingdon95** [mimiframework/Mimi.jl#677]
We need to be able to access the parameters and variables that are explicitly available at the composite level, probably via the following:
```
m[:top_composite_name, :exposed_variable_name]
```
I think we definitely need that method working for v1.0.0, which currently errors.

We had also discussed the ability to use dot-syntax to go down the tree to access values that maybe aren't bubbled up? something like:
```
m.top_composite.leaf_component.variable_name
```
But maybe that's not necessary for v1.0.0

**Comment by ckingdon95** [comment]
@lrennels I found this original issue for datum access methods, so I closed the other one

**Comment by lrennels** [comment]
#704
