### ISSUE TITLE
bug in `_fix_comp_path` for internal_param_conns

### ISSUE THREAD

**Issue by ckingdon95** [mimiframework/Mimi.jl#689]
There seems to be a bug (on master) in the way that the component paths in subcomponents' internal_param_conns get updated, but the bug only arises after three levels of composites. Here is an example:
```julia
using Mimi

@defcomp A begin
    v1 = Variable()
end

@defcomp B begin
    p1 = Parameter()
end

@defcomposite C begin
    Component(A)
    Component(B)
    connect(B.p1, A.v1)   # make an internal connection in comp C
end

@defcomposite D begin
    Component(C)
end

@defcomposite E begin
    Component(D)
end
```
This displays the correct src_comp_path and dst_comp_path:
```
julia> C.internal_param_conns
1-element Array{Mimi.InternalParameterConnection,1}:
 Mimi.InternalParameterConnection
  src_comp_path: ComponentPath(:C, :A)
  src_var_name: :v1
  dst_comp_path: ComponentPath(:C, :B)
  dst_par_name: :p1
  ignoreunits: false
  backup: nothing
  offset: 0
```
This one is also right:
```
julia> D[:C].internal_param_conns
1-element Array{Mimi.InternalParameterConnection,1}:
 Mimi.InternalParameterConnection
  src_comp_path: ComponentPath(:D, :C, :A)
  src_var_name: :v1
  dst_comp_path: ComponentPath(:D, :C, :B)
  dst_par_name: :p1
  ignoreunits: false
  backup: nothing
  offset: 0
```
But this one is messed up:
```

julia> E[:D][:C].internal_param_conns
1-element Array{Mimi.InternalParameterConnection,1}:
 Mimi.InternalParameterConnection
  src_comp_path: ComponentPath(:E, :D, :C, :C, :A)
  src_var_name: :v1
  dst_comp_path: ComponentPath(:E, :D, :C, :C, :B)
  dst_par_name: :p1
  ignoreunits: false
  backup: nothing
  offset: 0
```

**Comment by rjplevin** [comment]
Let me know if you guys want me to address this.

**Comment by ckingdon95** [comment]
Actually, it would be great if this is something that you could fix! Presumably it's a quick, somewhat isolated fix (but who knows...) would you be able to look at it soon?

**Comment by davidanthoff** [comment]
Yes, if this is an easy fix it would be great if you (@rjplevin) could do it!

**Comment by rjplevin** [comment]
And if it's not an easy fix? ;~)

**Comment by ckingdon95** [comment]
I'm imagining that this will only require modifying the `_fix_comp_path` function (and any helper functions if it has any). But if it starts touching other files or data structures, let's touch base before there are too many conflicts with the other stuff I'm working on!

**Comment by rjplevin** [comment]
I'm deep in another project right now, so I'll check in before I start on it. Feel free to take it on sooner!
