### ISSUE TITLE
Use REACT for Explorer

### ISSUE THREAD

**Issue by lrennels** [mimiframework/Mimi.jl#722]
Now that we have added components we want to allow things like a tree-view dive into composite components.  Motivated by this, we have decided to convert the framework over to REACT.  To-do items include converting the current framework over and getting that to work, followed by adding component viewing etc.

Currently being handled here:  #719

**Comment by davidanthoff** [comment]
Here are the UI libraries that I've heard from:
- https://developer.microsoft.com/en-us/fluentui#/get-started/web
- https://material-ui.com/
- https://semantic-ui.com/
- https://react-bootstrap.github.io/

I guess the first thing to check is which of these have some sort of support for the kind of hierarchical tree view thing that we need?

**Comment by lrennels** [comment]
The hierarchical tree view part would be for showing composite component structure, correct?  We also want a more advanced side-bar, but I'm guessing most of them have that.  I'll look into these now.
