### ISSUE TITLE
Combined timestep and range indexing doesn't work

### ISSUE THREAD

**Issue by davidanthoff** [mimiframework/Mimi.jl#748]
I tried this:
```julia
v.foo[TimestepIndex(1),:] .= 0
```
with this declaration:
```julia
foo= Variable(index=[time,4])
```
and that doesn't seem to work.

For now not a big problem because we can just do it manually, but it would be nice if this worked.

**Comment by lrennels** [comment]
@davidanthoff I'll work on this!

**Comment by lrennels** [comment]
Ah it looks like a `setindex!` problem, the `getindex` works ok
