### ISSUE TITLE
set_param! error message is confusing

### ISSUE THREAD

**Issue by jrising** [mimiframework/Mimi.jl#771]
If one uses `set_param!` to create a parameter specific to a given component, and then calls it a second time in the same way, the resulting error message is:
```
Cannot set parameter :<unique-param-name>, the model already has an external parameter with this name. Use `update_param(m, param_name, value)` to change the value, or use `set_param(m, comp_name, param_name, unique_param_name, value)` to set a value for only this component.
```
(also, presumably those functions should have a bang.)

I don't mind that there's not a single function to call that will update or create a component-specific parameter, but in this case, the error message should just say:
```
Cannot set parameter :<unique-param-name>: the component has already had this parameter set. Use `update_param!(m, unique_param_name, value)` to change the value for this component.
```

**Comment by lrennels** [comment]
@jrising thanks!  What would the actual call the user is typing look like in this case?  Are your saying that in the case that the user is _already_ using the method `set_param(m, comp_name, param_name, unique_param_name, value)`, so we can shorten the error message because it's implicitly clear that they want to do this for the specific component?

**Comment by jrising** [comment]
Actually, we can close this. The problem was more clear in the reference system, where the idea that you are actually "setting a parameter on a component" is implied. Will there be a way eventually to set parameters on components without constructing external parameter names?

Anyway, PR #773 fixes the situation for references, and users will better understand the error message if they get it when calling `set_param!` directlty.

**Comment by lrennels** [comment]
You can set a parameter in a component without explicitly constructing an external parameter with a call like `set_param!(m, :ComponentName, :ParameterName, 0.8)`, but then by default the external parameter it is linked to will also get the same `:ParameterName`. That's of course fine in some cases, but in others you may want to explicitly set a new external parameter name if this clashes with an existing component's parameter and you don't want the two of them to hold the same value and be linked together.

**Comment by jrising** [comment]
I understand that this function is creating a model-level parameter, but it sets up the illusion that it is setting the parameter at the component-level. I think the solution to this, however, is to create actual component-level parameters, not just to change the error message.
