### ISSUE TITLE
Mimi.jl/MimiFUND.jl compatability issue using other packages.

### ISSUE THREAD

**Issue by linguo4** [mimiframework/Mimi.jl#820]
Hi,

I plan to use the mimi package but there seems to be incompatibility to another package I'm using. The installation of Mimi.jl/MimiFUND.jl will downgrade my installed latest version ReinforcementLearning.jl. Please check the error and reply from the administrator of ReinforcementLearning.jl below. In the last reply, he mentioned the dependence from MimiFUND.jl on Distributions and DataStructures is not latest.
https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/issues/244#issuecomment-825328720

Could you please help me with this? Thank you!

**Comment by lrennels** [comment]
@linguo4 I think we fixed this together so I"m closing this issue, let me know if it's not fixed!
