### ISSUE TITLE
The d parameter is not typed enough

### ISSUE THREAD

**Issue by davidanthoff** [mimiframework/Mimi.jl#855]
It seems that the `d` parameter to our `run_timestep` function (and presumably also the `init` function) is not properly typed, leading to type instabilities down the road.

**Comment by lrennels** [comment]
We can probably use `NamedTuple` instead of `OrderedDict` for the dimensions dictionary, and perhaps other spots in the `Mimi` code like components, variables, and parameters dictionaries in order to get some more performance and from type stability inherent to those types.
